[package]
name = "multiboot2-header"
description = """
Library with type definitions and parsing functions for Multiboot2 headers.
This library is `no_std` and can be used in bootloaders.
"""
version = "0.5.0"
authors = [
    "Philipp Schuster <phip1611@gmail.com>"
]
license = "MIT/Apache-2.0"
edition = "2021"
categories = [
    "no-std",
    "parsing",
]
keywords = [
    "Multiboot2",
    "kernel",
    "boot",
    "bootloader",
]
# without this, sometimes crates.io doesn't show the preview of the README
# I expeciended this multiple times in the past
readme = "README.md"
homepage = "https://github.com/rust-osdev/multiboot2-header"
repository = "https://github.com/rust-osdev/multiboot2"
documentation = "https://docs.rs/multiboot2-header"
rust-version = "1.70"

[[example]]
name = "minimal"
required-features = ["builder"]

[features]
default = ["builder"]
alloc = []
builder = ["alloc"]
# Nightly-only features, which will eventually be stabilized.
unstable = []

[dependencies]
derive_more.workspace = true
log.workspace = true
ptr_meta.workspace = true
multiboot2 = { version = "0.22.0", default-features = false }
multiboot2-common = "0.1.0"

[package.metadata.docs.rs]
all-features = true
